[[target]]
name = "gsim"
description = "GHDL general-purpose simulations"
build = true
test = true
command = "python"
args = ["scripts/gsim.py"]

[[target]]
name = "msim"
description = "ModelSim general-purpose simulations"
build = true
test = true
command = "python"
args = ["scripts/msim.py"]
fileset.dofi = "{{ orbit.tb.name }}.do"

[[target]]
name = "xsim"
description = "Vivado Simulator general-purpose simulations"
build = true
test = true
command = "python"
args = ["scripts/xsim.py"]

[[target]]
name = "quartz"
description = "Intel Quartus Prime toolflow"
build = true
test = false
command = "python"
args = ["scripts/quartz.py"]
fileset.board = "*.board.toml"
fileset.bdf = "*.bdf"

[[target]]
name = "voodoo"
description = "Xilinx Vivado non-project mode toolflow"
build = true
test = false
command = "python"
args = ["scripts/voodoo.py"]
fileset.xdcf = "{{ orbit.top.name }}.xdc"

[[target]]
name = "xpro"
description = "Xilinx Vivado project mode toolflow"
build = true
test = false
command = "python"
args = ["scripts/xpro.py"]
fileset.xdcf = "*.xdc"
