[[target]]
name = "gee"
description = "GHDL general-purpose simulations"
command = ["python", "targets/gsim.py"]
build = true
test = true

[[target]]
name = "mojo"
description = "ModelSim general-purpose simulations"
command = ["python", "targets/mojo.py"]
build = true
test = true
fileset.dofi = "{{ orbit.tb.name }}.do"

[[target]]
name = "visi"
description = "Vivado Simulator general-purpose simulations"
command = ["python", "targets/xsim.py"]
build = true
test = true

[[target]]
name = "quartz"
description = "Intel Quartus Prime toolflow"
command = ["python", "targets/quartz.py"]
build = true
test = false
fileset.board = "*.board.toml"
fileset.bdf = "*.bdf"

[[target]]
name = "voodoo"
description = "Xilinx Vivado non-project mode toolflow"
command = ["python", "targets/voodoo.py"]
build = true
test = false
fileset.xdcf = "{{ orbit.top.name }}.xdc"

[[target]]
name = "xpro"
description = "Xilinx Vivado project mode toolflow"
command = ["python", "targets/xpro.py"]
build = true
test = false
fileset.xdcf = "*.xdc"

[[protocol]]
name = "git"
description = "Download ip using git"
command = ["git", "clone", "{{ orbit.ip.source }}", "-b", "{{ orbit.ip.version }}"]
patterns = ["*.git"]